title: Related Documents
theme: minima
collections:
  docs:
    output: true
header_pages:
  - index.md
  - index-vi.md
  - index-ja.md
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: pages
    values:
      nav_exclude: true
markdown_ext: "md,markdown"
titles_from_headings:
  enabled: false
