name: Build indexes

on:
  push:
    paths:
      - "**/*.md"
      - "scripts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pyyaml
      - run: python scripts/build-index.py
      - name: Commit indexes
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add **/index.md
          git commit -m "chore: refresh folder indexes" || echo "no changes"
          git push
